### ISSUE TITLE
Hide minus button and input when there is no products

### ISSUE THREAD

**Issue by Saneesh** [revolunet/angular-stepper#20]
Hello,
Here is the scenario I'm looking for. In my product list for each product, I want to show only the plus(+) symbol at first, when the user press the plus it should show "- 1 +" so that the user can decrement the value. Once there is no items it should show only the plus.

How can I achieve this with angular-stepper?

Thank you.

**Comment by revolunet** [comment]
Hi

If i understand correctly, you want to hide "disabled" elements ?
If so you could do it in pure css, selecting the disabled element and applying `display:none`

If you need more logic, you can edit the directive template directly or use a [decorator](https://docs.angularjs.org/guide/decorators)

**Comment by Saneesh** [comment]
Thank you very much!
css solution I tried like this but failed.

```
div[rn-stepper] button[disabled]{
  display:none;
}

div[rn-stepper] input[disabled] {
  display:none;
}
```

Then solved it with decorator, as you said.
('ng-hide' used to hide decriment button and input box with the same condition of 'ng-disabled')

This is the solution, if someone interested:

```
myApp.config(['$provide', function ($provide) {
    $provide.decorator('rnStepperDirective', function ($delegate) {
      var directive = $delegate[0];

      directive.template = [
        '<button ng-hide="isOverMin() || ngDisabled" type="button" ng-disabled="isOverMin() || ngDisabled" ng-click="decrement()">-</button>',
        '<input ng-hide="isOverMin() || ngDisabled" maxlength="2" type="text" ng-model="ngModel" ng-disabled="ngDisabled">',
        '<button type="button" ng-disabled="isOverMax() || ngDisabled" ng-click="increment()">+</button>'].join("");

      return $delegate;
    });
  }]);
```

**Comment by revolunet** [comment]
thanks for reporting 👍
